# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "ntfy_config_dir_path", "new": "ntfy_config_path" }
    - { "old": "ntfy_attachment_cache_dir_path", "new": "ntfy_attachment_cache_path" }

- name: Fail if required ntfy settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - ntfy_identifier
    - ntfy_uid
    - ntfy_gid
    - ntfy_hostname
    - ntfy_path_prefix
    - ntfy_container_network

- name: Run if Traefik is enabled
  when: ntfy_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for ntfy are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - ntfy_container_labels_traefik_hostname
        - ntfy_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `ntfy_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if ntfy_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          ntfy_container_labels_traefik_path_prefix (`{{ ntfy_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/ntfy`).
      when: "ntfy_container_labels_traefik_path_prefix != '/' and ntfy_container_labels_traefik_path_prefix[-1] == '/'"

- name: Run if ntfy email notification is enabled
  when: ntfy_smtp_sender_enabled | bool
  block:
    - name: Fail if required ntfy email notification settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - ntfy_smtp_sender_addr_host
        - ntfy_smtp_sender_from
